version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://myuser:mypassword@mongodb:27017

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongodb-data:/data/db


volumes:
  mongodb-data:
    