POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "name": "saitama",
  "email": "saitama@gmail.com",
  "password": "password123"
}

### post login
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "saitama@gmail.com",
  "password": "password123"
}


### create new user
POST http://27.112.78.205:8000/api/v1/auth/register
Content-Type: application/json

{
  "name": "saitama",
  "email": "saitama@gmail.com",
  "password": "password123"
}

### post login
POST http://27.112.78.205:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "saitama@gmail.com",
  "password": "password123"
}