POST http://localhost:3000/api/v1/notes
Content-Type: application/json

{
  "title": "Sample Note",
  "content": "This is a sample note content.",
  "author": "Dena"
}

### get notes
GET http://localhost:3000/api/v1/notes


### update notes by id
PUT http://localhost:3000/api/v1/notes/66b5b20a47aef26f53a27817
Content-Type: application/json

{
  "title": "Updated Note Title",
  "content": "This is updated content.",
  "author": "Singgih Septian Nugraha"
}

### delete notes by id
DELETE http://localhost:3000/api/v1/notes/66b59a9547aef26f53a27804
