POST http://localhost:8000/api/v1/notes
Content-Type: application/json

{
  "title": "Sample Note",
  "content": "This is a sample note content.",
  "author": "Meliodas"
}

### get notes
GET http://localhost:8000/api/v1/notes


### update notes by id
PUT http://localhost:8000/api/v1/notes/66b5b20a47aef26f53a27817
Content-Type: application/json

{
  "title": "Kuda Troya: Strategi di Balik Penipuan",
  "content": "Dalam mitos kuno Yunani, Kuda Troya adalah strategi cerdas yang digunakan oleh pasukan Yunani untuk menembus pertahanan kota Troya, yang telah mereka kepung selama sepuluh tahun. Para pahlawan Yunani, setelah gagal menembus tembok kota, membangun sebuah kuda kayu raksasa yang berongga dan menempatkan sekelompok prajurit di dalamnya. Mereka kemudian meninggalkan kuda itu di luar gerbang Troya sebagai hadiah dan menarik diri seolah-olah telah menyerah. Warga Troya, percaya bahwa kemenangan telah diraih dan kuda itu adalah simbol kemenangan, membawa kuda itu ke dalam kota. Malam harinya, para prajurit yang tersembunyi di dalam kuda keluar, membuka gerbang kota untuk pasukan Yunani yang telah kembali, dan akhirnya menghancurkan Troya dari dalam. Strategi ini terkenal sebagai contoh dari taktik penyusupan dan penipuan dalam perang.",
  "author": "Singgih Septian Nugraha"
}

### delete notes by id
DELETE http://localhost:8000/api/v1/notes/66b9f800fc407555e7155f8d

### Add a New Note
POST http://27.112.78.205:8000/api/v1/notes
Content-Type: application/json

{
  "title": "My New Note",
  "content": "This is the content of my new note."
}

